// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMfD8riSDtClIs957WovH7LOjnoAOj0lw',
    appId: '1:133090738495:web:3c160203cb00603066138a',
    messagingSenderId: '133090738495',
    projectId: 'fragrancekw-eab6f',
    authDomain: 'fragrancekw-eab6f.firebaseapp.com',
    storageBucket: 'fragrancekw-eab6f.appspot.com',
    measurementId: 'G-MNR7SSZTEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd0vSgO78MRS04ExBTalA9hHGH3BNLCeY',
    appId: '1:133090738495:android:4e7860ac93cb64dd66138a',
    messagingSenderId: '133090738495',
    projectId: 'fragrancekw-eab6f',
    storageBucket: 'fragrancekw-eab6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXArEIdIKmk3xnZ4AaM69XbyINkVmuCS4',
    appId: '1:133090738495:ios:16e8ef1cfe685c6a66138a',
    messagingSenderId: '133090738495',
    projectId: 'fragrancekw-eab6f',
    storageBucket: 'fragrancekw-eab6f.appspot.com',
    androidClientId: '133090738495-qlong34nj3o5f84og0trvsdfhdosljtb.apps.googleusercontent.com',
    iosClientId: '133090738495-ba2hgi15r0ne0knivcnl1akgksagsqjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fragrancekw.adminFragranceKw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXArEIdIKmk3xnZ4AaM69XbyINkVmuCS4',
    appId: '1:133090738495:ios:16e8ef1cfe685c6a66138a',
    messagingSenderId: '133090738495',
    projectId: 'fragrancekw-eab6f',
    storageBucket: 'fragrancekw-eab6f.appspot.com',
    androidClientId: '133090738495-qlong34nj3o5f84og0trvsdfhdosljtb.apps.googleusercontent.com',
    iosClientId: '133090738495-ba2hgi15r0ne0knivcnl1akgksagsqjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fragrancekw.adminFragranceKw',
  );
}
